metadata:
  name: openebs-${THIS_NAMESPACE}
  namespace: argocd
spec:
  destination:
    namespace: ${THIS_OPENEBS_NAMESPACE}
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=false
  source:
    path: charts/openebs
    repoURL: ${THIS_REPO_URL}
    targetRevision: HEAD
    helm:
      values: |
        openebs-crds:
          csi:
            volumeSnapshots:
              enabled: true
              keep: true
        localpv-provisioner:
          rbac:
            create: true
        zfs-localpv:
          crds:
            zfsLocalPv:
              enabled: false
            csi:
              volumeSnapshots:
                enabled: false
        lvm-localpv:
          crds:
            lvmLocalPv:
              enabled: true
            csi:
              volumeSnapshots:
                enabled: false
        engines:
          local:
            lvm:
              enabled: ${THIS_OPENEBS_ENGINE_LVM}
            zfs:
              enabled: ${THIS_OPENEBS_ENGINE_ZFS}
          replicated:
            mayastor:
              enabled: ${THIS_OPENEBS_ENGINE_MAYASTOR}
        
        loki:
          enabled: true
          # NOTE: For all possible storage options for loki, check https://github.com/openebs/openebs/blob/HEAD/charts/loki-storage.md
          # Configuration for loki's localpv hostpath storage class.
          localpvScConfig:
            enabled: true
            loki:
              # Name of loki's localpv hostpath storage class.
              name: "openebs-loki-localpv"
              # -- Host path where local loki data is stored in.
              basePath: "/var/local/{{ .Release.Name }}/localpv-hostpath/loki"
              # -- ReclaimPolicy of loki's localpv hostpath storage class.
              reclaimPolicy: Delete
              # -- VolumeBindingMode of loki's localpv hostpath storage class.
              volumeBindingMode: WaitForFirstConsumer
            minio:
              # Name of minio's localpv hostpath storage class.
              name: "openebs-minio-localpv"
              # -- Host path where local minio data is stored in.
              basePath: "/var/local/{{ .Release.Name }}/localpv-hostpath/minio"
              # -- ReclaimPolicy of minio's localpv hostpath storage class.
              reclaimPolicy: Delete
              # -- VolumeBindingMode of minio's localpv hostpath storage class.
              volumeBindingMode: WaitForFirstConsumer
        
          loki:
            serviceLabels:
              app: loki
            podLabels:
              app: loki
            schemaConfig:
              configs:
                - from: 2024-04-01
                  store: tsdb
                  object_store: s3
                  schema: v13
                  index:
                    prefix: loki_index_
                    period: 24h
            commonConfig:
              replication_factor: 3
        
            ingester:
              chunk_encoding: snappy
              # Configure these if a quicker ingestion is needed, i.e. faster push to your bucket.
              # chunk_idle_period: 3m
              # chunk_retain_period: 1m
              # max_chunk_age: 6m
            tracing:
              enabled: true
            querier:
              max_concurrent: 1
            limits_config:
              ingestion_burst_size_mb: 1000
              ingestion_rate_mb: 10000
              max_label_names_per_series: 20
        
          singleBinary:
            replicas: 3
            drivesPerNode: 1
            persistence:
              # -- Enabled persistence for loki
              enabled: true
              # -- Storage class for loki storage
              storageClass: "openebs-loki-localpv"
              accessModes:
                - ReadWriteOnce
              # -- Size of loki local storage volume
              size: ${THIS_DEFAULT_STORAGE_SIZE}
        
          minio:
            replicas: 3
            drivesPerNode: 1
            mode: distributed
            # Disable this if you want to enabled external s3 bucket, and uncomment the storage section above.
            enabled: true
            persistence:
              # -- Enabled persistence for minio
              enabled: true
              # -- Storage class for minio storage
              storageClass: "openebs-minio-localpv"
              # -- Size of minio local storage volume
              size: ${THIS_DEFAULT_STORAGE_SIZE}
        
          deploymentMode: SingleBinary
        
          lokiCanary:
            enabled: false
        
          chunksCache:
            enabled: false
        
          test:
            enabled: false
        
          gateway:
            enabled: false
        
          resultsCache:
            enabled: false
        
          backend:
            replicas: 0
          read:
            replicas: 0
          write:
            replicas: 0
        
          ingester:
            replicas: 0
          querier:
            replicas: 0
          queryFrontend:
            replicas: 0
          queryScheduler:
            replicas: 0
          distributor:
            replicas: 0
          compactor:
            replicas: 0
          indexGateway:
            replicas: 0
          bloomCompactor:
            replicas: 0
          bloomGateway:
            replicas: 0
        
        alloy:
          enabled: true
        
          logging_config:
            # Enable debugging on alloy components.
            debugging: false
            # -- Labels to enable scraping on, at-least one of these labels should be present.
            labels:
              openebs.io/logging: true
            # -- X-Scope-OrgID to pe populated which pushing logs. Make sure the caller also uses the same.
            tenant_id: openebs
        # Refer to https://github.com/openebs/mayastor-extensions/blob/v2.8.0/chart/values.yaml for complete set of values.
        mayastor:
          nodeSelector: {}
          image:
            registry: ghcr.io/dzervas
            repo: openebs
          io_engine:
            nodeSelector:
              # Keep only the engine nodeSelector and get rid of the arch
              "openebs.io/engine": mayastor
          csi:
            image:
              registry: ghcr.io/dzervas
              repo: openebs
            node:
              initContainers:
                enabled: false
        
          etcd:
            image:
              # The 3.5.6 image used by the etcd version in the mayastor helm chart
              # is not available for arm64
              tag: 3.5-debian-12
            volumePermissions:
              image:
                repository: bitnami/os-shell
