apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: ${THIS_NAMESPACE}
  annotations:
    cert-manager.io/cluster-issuer: ${THIS_CLUSTER_ISSUER}
    nginx.ingress.kubernetes.io/rewrite-target: /
    spec.ingressClassName: ${THIS_CLUSTER_INGRESS}
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    #traefik.ingress.kubernetes.io/router.middlewares: example-redirect-https@kubernetescrd
spec:
  ingressClassName: ${THIS_CLUSTER_INGRESS}
  tls:
    - hosts:
      - ${THIS_KEYCLOAK_HOST}.${THIS_DOMAIN}
      secretName: chart-${THIS_NAMESPACE}-${THIS_KEYCLOAK_HOST}-tls
  rules:
    - host: ${THIS_KEYCLOAK_HOST}.${THIS_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
