apiVersion: v1
kind: Service
metadata:
  name: raymii-mosquitto-svc-nodeport
  namespace: raymii-mosquitto-dev
spec:
  type: NodePort
  selector:
    app: raymii-mosquitto
    role: primary
  ports:    
  - name: mqtt
    nodePort: 31883
    port: 1883
    targetPort: 1883
    protocol: TCP
