apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${THIS_NAME}-minio-env-configuration
  namespace: ${THIS_NAMESPACE}
stringData:
  config.env: |-
    export MINIO_ROOT_USER="${THIS_MINIO_ACCESS_KEY}"
    export MINIO_ROOT_PASSWORD="${THIS_MINIO_SECRET_KEY}"
