apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${THIS_ARGO_HOST}-${THIS_NAME}-cert"
  namespace: argocd
spec:
  secretName: "${THIS_ARGO_HOST}-${THIS_NAME}-tls"
  dnsNames:
    -  "${THIS_ARGO_HOST}.${THIS_DOMAIN}"
  issuerRef:
    kind: ClusterIssuer
    name: ${THIS_CLUSTER_ISSUER}
