apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: ${THIS_NAMESPACE}-postgres
  namespace: ${THIS_NAMESPACE}

spec:

   replicas: 1
   image: postgres:17-alpine

   database:
      size: 8000Mi
      storageClassName:  "${THIS_STORAGECLASS}"

   customConfig: ${THIS_NAMESPACE}-postgres-conf

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: ${THIS_SECRETS}
              key: db-admin-pass
      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: ${THIS_SECRETS}
              key: replicationUserPassword
      - name: POSTGRES_NC_DB_PASSWORD
        valueFrom:
            secretKeyRef:
              name: ${THIS_SECRETS}
              key: nc-db-password 
      - name: POSTGRES_OPENPROJECT_DB_PASSWORD
        valueFrom:
            secretKeyRef:
              name: ${THIS_SECRETS}
              key: op-db-password 
