
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: ${THIS_CLUSTER_ISSUER}
    nginx.ingress.kubernetes.io/rewrite-target: /
    spec.ingressClassName: ${THIS_CLUSTER_INGRESS}
    #traefik.ingress.kubernetes.io/router.middlewares: example-redirect-https@kubernetescrd
  labels:
    app.kubernetes.io/instance: openbao-ui
  name: openbao-ui
  namespace: ${THIS_NAME}
spec:
  ingressClassName: ${THIS_CLUSTER_INGRESS}
  #ingressClassName: traefik
  rules:
  - host: ${THIS_BAOUI_HOST}.${THIS_DOMAIN}
    http:
      paths:
      - backend:
          service:
            name: openbao-ui
            port:
              number: 8200
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ${THIS_BAOUI_HOST}.${THIS_DOMAIN}
    secretName: chart-${THIS_NAME}-${THIS_BAOUI_HOST}-tls
